import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import IsAuthContext from "./ContextAPI/IsAuthContext";
import SingleFoodContext from "./ContextAPI/SingleFoodContext";
import PaymentContext from "./ContextAPI/PaymentContext";
import AuthFormContext from "./ContextAPI/AuthFormContext";
import IsUserAuthContext from "./ContextAPI/IsUserAuthContext";
import SetMenu from "./ContextAPI/SetMenu";

import ArrowTop from "./components/ArrowTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chitto Khaja",
  description: "Generated by create next app",
  icons: {
    icon: "/admin/food_logo.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SingleFoodContext>
          <PaymentContext>
            <AuthFormContext>
              <IsUserAuthContext>
                <IsAuthContext>
                  <SetMenu>
                    <Toaster
                      position="top-right"
                      reverseOrder={false}
                      gutter={10}
                      toastOptions={{
                        className: "",
                        duration: 5000,
                        removeDelay: 100,
                      }}
                    />
                    {children}
                    <ArrowTop />
                  </SetMenu>
                </IsAuthContext>
              </IsUserAuthContext>
            </AuthFormContext>
          </PaymentContext>
        </SingleFoodContext>
      </body>
    </html>
  );
}
