import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import IsAuthContext from "./ContextAPI/IsAuthContext";
import SingleFoodContext from "./ContextAPI/SingleFoodContext";
import ArrowTop from "./components/ArrowTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SingleFoodContext>
          <IsAuthContext>
            <Toaster
              position="top-right"
              reverseOrder={false}
              gutter={10}
              toastOptions={{
                className: "",
                duration: 5000,
                removeDelay: 100,
              }}
            />
            {children}
            <ArrowTop />
          </IsAuthContext>
        </SingleFoodContext>
      </body>
    </html>
  );
}
